### ISSUE TITLE
PyCall.symbols_present is false

### ISSUE THREAD

**Issue by abalkin** [JuliaPy/pyjulia#128]
When PyCall is imported from a Julia instance embedded in python, it should obtain python symbols directly from the executable and not reload libpython.  However,

```python
>>> import julia
>>> j = julia.Julia()
>>> j.eval("PyCall.symbols_present")
False
```

and

```python
>>> j.eval("PyCall.@pysym :xyz")
('xyz', '/usr/local/opt/python36/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m')
```

**Comment by tkf** [comment]
I think we are doing it already when using fake-julia (for statically linked Python).  If you are using dynamically linked Python, it deos make sense to load it from libpython (because Python does it as well).

Note that fake-julia does not work in Julia 0.7 or above.  This issue is tracked by #173.
