### ISSUE TITLE
Julia object has no attribute Any

### ISSUE THREAD

**Issue by zekeriyasari** [JuliaPy/pyjulia#144]
Although it is possible to access any built-in Julia function, it is not possible to access any of the Julia built-in Julia types. For example, the script
```python
from julia import Julia
jul = Julia()
print(jul.sind)
print(jul.Any)
```
gives the output:
```python
<PyCall.jlwrap sind>
Traceback (most recent call last):
  File "/user/zekeriya.sari/Documents/AtomProjects/PyJUlia/test.py", line 5, in <module>
    print(jul.Any)
AttributeError: 'Julia' object has no attribute 'Any'
```
I did not see any information about this issue in the documentation and in the test codes of `pyjulia`.  I wonder if it is possible to access these built-in Julia types in python side. (See https://github.com/JuliaPy/PyCall.jl/issues/460). Any suggestions?

**Comment by stevengj** [comment]
Yes, it looks like it currently only exports the functions in Base (https://github.com/JuliaPy/pyjulia/blob/master/julia/core.py#L386).

Honestly, the whole current approach seems broken to me… I feel like it should load symbols in the module(s) lazily, rather than adding them all as attributes when the module is loaded.

For now, you can presumably do `jul.eval("Any")`?

**Comment by zekeriyasari** [comment]
`jul.eval("Any")` works fine. Thank you for all.
