### ISSUE TITLE
CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status -11

### ISSUE THREAD

**Issue by casv2** [JuliaPy/pyjulia#303]
Everything seems to work, julia.install() ran fine and it found the right  the right Julia and vice versa

```
>>> from julia import Julia
>>> Julia()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/casv2/miniconda2/lib/python2.7/site-packages/julia/core.py", line 1205, in __init__
    self.__julia = Julia(*args, **kwargs)
  File "/home/casv2/miniconda2/lib/python2.7/site-packages/julia/core.py", line 953, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "/home/casv2/miniconda2/lib/python2.7/site-packages/julia/core.py", line 433, in load
    retcode, [julia, "-e", "..."], output
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status -11
>>> 
```

I get this error though. Does anyone have an idea?

**Comment by tkf** [comment]
`returned non-zero exit status -11` means that Julia had a segmentation fault, presumably while running this script:

https://github.com/JuliaPy/pyjulia/blob/a90aa32945f9210ab620f47e280ac4f5f8aee29b/src/julia/core.py#L341-L369

The most obvious suspect is `unsafe_string(Base.JLOptions().image_file)`.  It may be useful to check `Base.JLOptions()` in Julia REPL.

**Comment by casv2** [comment]
Thanks you were right. Reinstalling Julia seems to have fixed the problem!

**Comment by fxjaeckel** [comment]
If you come across this on Ubuntu (Julia 1.5.3, Ubuntu 21.04 pre-release julia/1.5.3+dfsg-3 ), the error results from
`println(Libdl.dlpath(string("lib", splitext(Base.julia_exename())[1])))`
because it can't find the shared library `libjulia.so`. 
This can be fixed by `sudo ln /usr/lib/x86_64-linux-gnu/libjulia.so.1 /usr/lib/x86_64-linux-gnu/libjulia.so` as suggested in [](https://github.com/JuliaLang/PackageCompiler.jl/issues/280).
